
SET(BOOST_ROOT "${NIMBUS_ROOT}/extern/boost")
SET(LEVELDB_ROOT "${NIMBUS_ROOT}/extern/leveldb")
SET(PROTOBUF_ROOT "${NIMBUS_ROOT}/extern/protobuf")

SET(IFLAGS "-I${NIMBUS_ROOT}")
LIST(APPEND IFLAGS "-I${BOOST_ROOT}/include")
LIST(APPEND IFLAGS "-I${LEVELDB_ROOT}/include")
LIST(APPEND IFLAGS "-I${PROTOBUF_ROOT}/include")
