#!/usr/bin/python

import os
import sys
import optparse
from struct import *

parser = optparse.OptionParser("usage: %prog [options] input.obj output.tri")
parser.add_option('-s','--scale',default=1,type='float',help='multiply input positions by scale factor')
parser.add_option('-f','--flip',action='store_true',help='flip orientation of triangles')
(options,args)=parser.parse_args()
if len(args)!=2: parser.error("invalid number of arguments")
scale=options.scale

input=open(args[0],'r')
if args[1][-3:]=='.gz':
    output=os.popen('gzip -c > '+args[1],'w')
else:
    output=open(args[1],'w')

vertices=[]
triangles=[]
for line in input:
    words=line.split()
    if not len(words): continue
    type=words[0]
    args=words[1:]
    if type=='#': pass
    elif type=='v':
        assert(len(args)==3)
        vertices.append(map(float,args))
    elif type=='nv': pass
    elif type=='f':
        v=map(lambda t:int(t.split('/')[0]),args)
        for i in range(len(v)-2):
            triangles.append([v[0],v[i+1],v[i+2]])
    else: pass #assert(false)

# flip if desired
if options.flip:
    for t in triangles:
        t[1],t[2]=t[2],t[1]

# write triangle mesh
output.write(pack('i',len(vertices)))
output.write(pack('ii',3,len(triangles)))
for t in triangles: output.write(pack('iii',t[0],t[1],t[2]))

# write particle state
output.write(pack('=biii',1,len(vertices),len(vertices),10))
output.write(pack('bbb',0,0,0))

# write positions
output.write(pack('i',len(vertices)))
for p in vertices: output.write(pack('fff',p[0]*scale,p[1]*scale,p[2]*scale))
