#!/usr/bin/python

import re
import fileinput
from math import *

times={}

for line in fileinput.input():
    m=re.match('(\w+)\s+(\S+)m(\S+)s',line);
    if not m:continue
    assert(m.group(2)=='0')
    times.setdefault(m.group(1),[]).append(float(m.group(3)))

def mean(a):
    return sum(a)/len(a)

def stddev(a,mean):
    return sqrt(reduce(lambda x,y:x+(y-mean)**2,a)/(len(a)-1))

for name,a in times.items():
    m=mean(a)
    s=stddev(a,m) 
    print "%s = %g +- %g"%(name,m,s)
