#!/bin/bash

for i in {1..10}
do
  echo "trial: $i started"

  echo -e "${Pur}launching scheduler version I ...${RCol}"
  ../scheduler_v1/scheduler 1  > scheduler.txt &
  sleep 1
 
  echo -e "${Pur}launching stencil worker multi number 1 ...${RCol}"
  ../stencil_1d/worker 1 > worker.txt

  echo "trial: $i passed"
done

echo "all trials pased, cleaning up ..."
rm worker.txt scheduler.txt
