#include <PhysBAM_Tools/Vectors/VECTOR.h>
#include <PhysBAM_Dynamics/Particles/PARTICLES_FORWARD.h>
#include "CODIMENSIONAL_FLUID_PARTICLES.h"

namespace PhysBAM{

template<class TV> CODIMENSIONAL_FLUID_PARTICLES<TV>::
CODIMENSIONAL_FLUID_PARTICLES(){}

template<class TV> CODIMENSIONAL_FLUID_PARTICLES<TV>::
~CODIMENSIONAL_FLUID_PARTICLES(){}

template class CODIMENSIONAL_FLUID_PARTICLES<VECTOR<float,1> >;
template class CODIMENSIONAL_FLUID_PARTICLES<VECTOR<float,2> >;
template class CODIMENSIONAL_FLUID_PARTICLES<VECTOR<float,3> >;
#ifndef COMPILE_WITHOUT_DOUBLE_SUPPORT
template class CODIMENSIONAL_FLUID_PARTICLES<VECTOR<double,1> >;
template class CODIMENSIONAL_FLUID_PARTICLES<VECTOR<double,2> >;
template class CODIMENSIONAL_FLUID_PARTICLES<VECTOR<double,3> >;
#endif
}
